version: "3.9"
services:
  # 1. MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  # 2. Kafka
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    user: root
    ports:
      - "9092:9092"   # Internal listener for containers
      - "9093:9093"   # Controller listener
      - "9094:9094"   # External listener for host access
    environment:
  
      # KRaft configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CLUSTER_ID: my-cluster-id-123
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Multi-listener setup
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${PUBLIC_DOMAIN:-localhost}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Broker tuning for dev  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Logging
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=
    depends_on:
      - kafka

  # 3. PostgreSQL for Airflow metadata
  postgres:
    image: postgres:14
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/

  # 4. Redis      
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data


  # 5. Airflow + Scrapy Environment
  airflow:
    build:
      context: ..
      dockerfile: docker/airflow.dockerfile
    container_name: airflow_scrapy
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_HOME: /app/airflow
    depends_on:
      - postgres
      - kafka
      - minio
    volumes:
      - ../airflow/dags:/app/airflow/dags
      - ../scrapy_project:/app/scrapy_project
      - ../airflow/logs:/app/airflow/logs
    command: >
      bash -c "
      echo 'ðŸ”§ Running Airflow standalone mode...' &&
      exec airflow standalone"

  news_ingestion_worker:
    build:
      context: ..
      dockerfile: docker/news-ingestion.dockerfile
    container_name: news_ingestion_worker
    volumes:
      - ./workers/news_ingestion_worker:/app/news_ingestion_worker
    depends_on:
      - kafka
      - minio
      - postgres
    command: python /app/news_ingestion_worker/news_ingestion_worker.py
    restart: unless-stopped
