version: "3.9"
services:
  # 1. MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio_data:/data

  # 2. Kafka
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    user: root
    ports:
      - "9092:9092"   # Internal listener for containers
      - "9093:9093"   # Controller listener
      - "9094:9094"   # External listener for host access
    environment:
  
      # KRaft configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CLUSTER_ID: my-cluster-id-123
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Multi-listener setup
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${PUBLIC_DOMAIN:-localhost}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Broker tuning for dev  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Logging
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./volumes/kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=
    depends_on:
      - kafka

  # 3. PostgreSQL for Airflow metadata
  postgres:
    image: postgres:14
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql

  # 4. Redis      
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./volumes/redis_data:/data


  # 5. Airflow + Scrapy Environment
  airflow:
    build:
      context: ..
      dockerfile: docker/airflow.dockerfile
    container_name: airflow_scrapy
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_HOME: /app/airflow
    depends_on:
      - postgres
      - kafka
      - minio
    volumes:
      - ../airflow/dags:/app/airflow/dags
      - ../scrapy_project:/app/scrapy_project
      - ../airflow/logs:/app/airflow/logs
    command: >
      bash -c "
      echo 'ðŸ”§ Running Airflow standalone mode...' &&
      exec airflow standalone"

  news_ingestion_worker:
    build:
      context: ..
      dockerfile: docker/news-ingestion.dockerfile
    container_name: news_ingestion_worker
    volumes:
      - ../workers/news_ingestion_worker:/app/news_ingestion_worker
    depends_on:
      - kafka
      - minio
      - postgres
    command: python /app/news_ingestion_worker/news_ingestion_worker.py
    restart: unless-stopped
  
  # 6. Hive Metastore Service
  hive-metastore:
    image: bitsondatadev/hive-metastore:latest
    container_name: hive-metastore
    depends_on:
      - postgres
    environment:
      METASTORE_DB_TYPE: postgres
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_DB_PORT: 5432
      METASTORE_DB_NAME: metastore
      METASTORE_DB_USER: ${DB_USER:-airflow}
      METASTORE_DB_PASSWORD: ${DB_PASSWORD:-airflow}
    ports:
      - "9083:9083"
    volumes:
      - ./hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
      - ./hive-metastore/lib/postgresql-42.7.8.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/postgresql-42.7.8.jar
      - ./hive-metastore/lib/aws-java-sdk-bundle-1.11.375.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/aws-java-sdk-bundle-1.11.375.jar
      - ./hive-metastore/lib/hadoop-auth-3.2.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hadoop-auth-3.2.4.jar
      - ./hive-metastore/lib/hadoop-aws-3.2.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hadoop-aws-3.2.4.jar
      - ./hive-metastore/lib/hadoop-common-3.2.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hadoop-common-3.2.4.jar
      - ./hive-metastore/lib/hadoop-hdfs-3.2.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hadoop-hdfs-3.2.4.jar
      - ./hive-metastore/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]

  # 7. Trino Query Engine
  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - hive-metastore
    ports:
      - "8081:8080"
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog